### ISSUE TITLE
Version 0.2 is not on crates.io

### ISSUE THREAD

**Issue by martinsp** [posborne/rust-gpio-cdev#12]
Installation instructions in the readme uses version 0.2, but it looks like 0.2 is not published on crates.io

```bash
    Updating crates.io index
error: failed to select a version for the requirement `gpio-cdev = "^0.2"`
  candidate versions found which didn't match: 0.1.0
  location searched: crates.io index
```

**Comment by fpagliughi** [comment]
I had updated the readme as part of PR #10, which made it to master but wasn't published.
@posborne Is there a reason this was not published to crates.io?

**Comment by posborne** [comment]
:man_facepalming: Published now.  Apparently I failed to finish that task up.
